name: Architecture Review POC - Copilot Analysis

# This workflow creates an issue asking Copilot to review architecture documentation against code
on:
  workflow_dispatch:
    inputs:
      message:
        description: Custom context or focus area for the review (optional)
        required: false
        default: General architecture alignment review
        type: string

permissions:
  contents: read
  issues: write

jobs:
  test-architecture-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Architecture Review Issue for Copilot
        id: create-issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const currentTime = new Date().toLocaleString();
            const reviewId = currentTime.replace(/[^0-9]/g, '');
            
            const issueBody = [
              "## 📋 Architecture Documentation Review Request",
              "",
              `**Triggered at**: ${currentTime}`,
              `**Workflow run**: ${{ github.run_id }}`,
              `**Focus area**: ${{ inputs.message }}`,
              "",
              "---",
              "",
              "@github-copilot Hello! 👋",
              "",
              "I need you to review the current **ARCHITECTURE.md** documentation against the actual codebase in this repository to identify any discrepancies or needed updates.",
              "",
              "## 📋 **Your Task:**",
              "",
              "1. **Read the ARCHITECTURE.md file** in the repository root",
              "2. **Analyze the current codebase structure** (especially the `src-v2/` directory)",
              "3. **Compare the documentation against the actual code**",
              "4. **Identify any gaps, inaccuracies, or needed updates**",
              "",
              "⚠️ **EXCLUDE from analysis**: Do not review the `test/` directory - this contains test code and is not part of the architecture documentation scope.",
              "",
              "## 🎯 **What to look for:**",
              "",
              "- **File paths and structure** - Are the documented paths correct?",
              "- **Service/controller methods** - Do the documented methods exist?", 
              "- **Dependencies and integrations** - Are external APIs and libraries accurate?",
              "- **Architecture patterns** - Does the actual code match the documented architecture?",
              "- **Missing components** - Are there new files/services not documented?",
              "",
              "## 📝 **Expected Output:**",
              "",
              "**If changes are needed:**",
              "- Create a PR with updates to ARCHITECTURE.md",
              "- Fix any incorrect file paths, methods, or descriptions", 
              "- Add documentation for any missing components",
              "- Explain in the PR description what was outdated and how you fixed it",
              "",
              "**If no changes are needed:**",
              "- Simply comment on this issue confirming the review is complete",
              "- State that the architecture documentation is accurate and up-to-date",
              "- Note the review date and any observations",
              "- Do NOT create a PR or any files if no changes are needed",
              "",
              "---",
              "",
              "**Repository Context:**",
              "- Main backend code: `src-v2/` directory",
              "- Frontend code: `public/js/modules/` directory",
              "- Configuration: `config/` directory", 
              "- This is a Node.js app with PowerBI integration and OpenAI chat",
              "- **IGNORE**: `test/` directory (test code, not architecture)",
              "",
              "**Goal:** Keep our architecture documentation accurate and up-to-date!"
            ].join("\n");
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `📋 Architecture Documentation Review - ${currentTime}`,
              body: issueBody,
              labels: [
                'documentation',
                'architecture',
                'copilot-review',
                'automated-analysis'
              ]
            });

            console.log(`✅ Created architecture review issue #${issue.data.number}`);
            console.log(`🔗 Issue URL: ${issue.data.html_url}`);
            console.log(`⏰ Created at: ${currentTime}`);

            core.setOutput('issue-url', issue.data.html_url);
            core.setOutput('issue-number', issue.data.number);

      - name: Assign Issue to Copilot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.rest.issues.assignCopilot({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ steps.create-issue.outputs.issue-number }}
              });
              console.log(`✅ Successfully assigned issue to Copilot`);
            } catch (error) {
              console.log(`⚠️ Could not assign to Copilot automatically: ${error.message}`);
              console.log(`🤖 Manual assignment may be required`);
            }
            
      - name: Display Results
        run: |
          echo "🎉 Architecture Review Issue Created and Assigned!"
          echo "📋 Issue Number: ${{ steps.create-issue.outputs.issue-number }}"
          echo "🔗 Issue URL: ${{ steps.create-issue.outputs.issue-url }}"
          echo "🤖 Assigned to: Copilot (automatic)"
          echo ""
          echo "🔍 What Copilot will do next:"
          echo "1. Acknowledge with 👀 emoji"
          echo "2. Read ARCHITECTURE.md and analyze the codebase"
          echo "3. Create a PR with updates or confirmation report"
          echo "4. Compare documented vs actual file structure"
          echo ""
          echo "📝 This tests Copilot's code analysis and documentation skills!"
          echo "⏰ No manual steps required - Copilot should start working automatically!"